swiftmailer:
#    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport: 'smtp'
    host: 'smtp.gmail.com'
    username: 'ephilosia@gmail.com'
    password: '2070298Lucas*'
    encryption: 'tls'
    port: '587'